config/routes.rb
ProjectApp::Application.routes.draw do
  # Here namespace admin belongs to super admin role
  namespace :admin do
    resources :users, :settings, :footer_pages, :contacts, :languages, :email_templates, :schools
    get '/updateschool/:id' => 'schools#updateschool', :as => :updateschool
  end

  resources :user_sessions

  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup(/:registration_key)' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]

  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
  get 'dashboard' => 'fronts#dashboard', :as => :dashboard
  match 'activate/:activation_key' => 'fronts#user_activation', :as => :activation_link, via: [:get]
  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box
  match 'contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other

  # user schools
  #get '/schools' => 'schools#index', :as => :schools
  resources :schools

  # You can have the root of your site routed with "root"
  root 'fronts#dashboard'

end

app/controllers/fronts_controller.rb
class FrontsController < ApplicationController
  before_filter :require_user, :only => [:change_password, :profile]

  def dashboard
    unless current_user
      redirect_to signup_url
    end
  end
  
  def show_search_box
    @o_single = params[:model].constantize.new
    @params_arr = params[:pm].split(',')
  end 
  
  def destroy_model_data
    @o_single = params[:model].constantize.new
  end 

  #forgot password
  def forgot_password
    @user = User.new
    if params[:user]
      if user = authenticate_email(params[:user][:email])
        new_pass = SecureRandom.hex(5)
        user.password = user.password_confirmation = new_pass
        user.save

        #options
        opts = { :username => user.name, :new_pass => new_pass }

        #subject
        subject = t("general.reset_password")

        #send mail
        UserMailer.forgot_password_confirmation(user.email, subject, opts).deliver

        @user_session = UserSession.find
        if @user_session
          @user_session.destroy
        end
        session[:user_id] = nil
        flash[:notice] = t("general.password_has_been_sent_to_your_email_address")
        redirect_to forgot_password_path
      else
        flash[:forgot_pass_error] = t("general.no_user_exists_for_provided_email_address")
        redirect_to :action => "forgot_password"
      end
    end
  end

  #change password
  def change_password
    @o_single = User.find(current_user.id)
    if params[:user]
      @o_single.password = params[:user][:password]
      @o_single.password_confirmation = params[:user][:password_confirmation]
      @o_single.password_required = true
      respond_to do |format|
        if @o_single.update_attributes(user_params)
          format.html { redirect_to change_password_url, notice: t("general.password_successfully_updated") }
          format.json { head :no_content }
        else
          format.html { render action: 'change_password' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # signup user activation
  def user_activation
    if request.get?
      if params[:activation_key].present?
        @o_user = User.find(:first, :conditions => ["registration_key = ? AND is_active = ?", params[:activation_key], false])
        if @o_user
          @o_user.update(:is_active => true)          
          flash[:notice] = t("general.user_active_successfully")
        else
          flash[:notice] = t("general.already_activated")
        end
        redirect_to root_url
      end
    end
  end

  #profile
  def profile
    @o_single = User.find(current_user.id)
    if params[:user]
      respond_to do |format|
        if @o_single.update_attributes(user_params)
          format.html { redirect_to profile_url, notice: t("general.successfully_updated") }
          format.json { head :no_content }
        else
          format.html { render action: 'profile' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  #contact_us
  def contact_us
    if params[:contact]
      respond_to do |format|
        @o_single = Contact.new(contact_params)
        if @o_single.save
          format.html { redirect_to contact_us_url, notice: t("general.successfully_sent_inquiry") }
          format.json { head :no_content }
        else
          format.html { render action: 'contact_us' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end
    else
      @o_single = Contact.new        
    end
  end  
  
  #footer and other static pages
  def other
    @o_single = FooterPage.where(page_route: params[:page_id]).first
  end  

  private

    def contact_params
      params.require(:contact).permit!
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit!
    end

end

app/helpers/fronts_helper.rb
module FrontsHelper
end

app/views/fronts/_admin_dashboard.html.erb
<div class="page-header">
	<h4>
		<%= t("general.admin_dashboard") %>
	</h4>
</div>

app/views/fronts/_search.html.erb
<%= form_for @o_single, :method => "get", :remote => true, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend></legend>

 		<% @params_arr.each do |p| %>
	    <div class="control-group">
	      <%= f.label p.capitalize, :class => 'control-label' %>
	      <div class="controls">
	        <%= f.text_field p, :value => (session[:search_params] ? session[:search_params][p] : ""), :class => 'input-xlarge' %>
	      </div>
	    </div>
  	<% end %>
   <%# model_name = params[:model].downcase %>
    <div class="controls">
      <%= f.submit t("general.search"), :class => 'btn btn-primary', :id => 'search_button_id' %>
      <span data-no-turbolink>
      <%= link_to 'Cancel', 'javascript:void(0)', :onclick => '$(this).closest("form").closest("div").hide()', :class => 'btn' %></span>
    </div>

  </fieldset>

<% end %>

app/views/fronts/_superadmin_dashboard.html.erb
<div class="page-header">
	<h4>
		<%= t("general.admin_dashboard") %>
	</h4>
</div>

app/views/fronts/_user_dashboard.html.erb
<div class="page-header">
	<h4>
		<%= t("general.user_dashboard") %>
	</h4>
</div>

app/views/fronts/change_password.html.erb
<div class="page-header">
	<h4>
		<%= t("general.change_password") %>
	</h4>
</div>
<div class="container pt60">
	<%= form_for @o_single, :url => change_password_path, :html => { :class => 'form-horizontal' } do |f| %>
		<div class="control-group <%= @o_single.errors[:password].any? ? 'error' : '' %>">
					<%= f.label :password, :class => 'control-label' %><span class="redStart">*</span>
	        <div class="controls">
	            <%= f.password_field :password, :class => 'input-xlarge', :placeholder => t("general.password") %>
	       		<% if @o_single.errors[:password].any? %>
	        		<span class="help-inline"><%= @o_single.errors[:password].first %></span>
	      		<% end %>
	        </div>
	    </div>
		<div class="control-group <%= @o_single.errors[:password_confirmation].any? ? 'error' : '' %>">
					<%= f.label :password_confirmation, :class => 'control-label' %><span class="redStart">*</span>
	        <div class="controls">
	            <%= f.password_field :password_confirmation, :class => 'input-xlarge', :placeholder => t("general.password_confirmation") %>
	       		<% if @o_single.errors[:password_confirmation].any? %>
	        		<span class="help-inline"><%= @o_single.errors[:password_confirmation].first %></span>
	      		<% end %>
	        </div>
	    </div>

      <div class="form-actions">
          <div class="row-fluid mb10">
              <div class="span12">
                  <%= f.submit t("general.change_password"), :class => 'btn btn-primary' %>
              </div><!--/span-->
          </div><!--/row-->
      </div>
	<% end %>
</div>


app/views/fronts/contact_us.html.erb
<div class="page-header">
	<h4>
		<h4><%= t("general.contact_us") %></h4>
	</h4>
</div>
<div class="container pt60">
<%= form_for @o_single, :url => contact_us_path, :html => { :class => 'form-horizontal' } do |f| %>


    <div class="control-group">
      <label class = 'control-label'><%= t("general.your_name") %></label><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :name, :class => 'input-xlarge' %>
       	<% if @o_single.errors[:name].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:name].first %></span>
      	<% end %>        
      </div>
    </div>
    
    <div class="control-group">
      <label class = 'control-label'><%= t("general.your_email") %></label><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :email, :class => 'input-xlarge' %>
       	<% if @o_single.errors[:email].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:email].first %></span>
      	<% end %>                
      </div>
    </div>
    	
    <div class="control-group">
    	<div class="controls">
    	<%= t("general.type_your_msg_here") %>
    	<div class="clearBoth"></div>    	
    	<%= f.text_area :message, :class => 'textArea wysihtml5' %>
    	</div>
    </div>


    <div class="form-actions">
      <%= f.submit t("general.send"), :class => 'btn btn-primary' %>
    </div>
    

<% end %>
</div>

<script type="text/javascript">
	$(document).on('page:load', function(){
	  window['rangy'].initialized = false
	})
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/fronts/dashboard.html.erb
<%= render "#{current_user.role.role_type.downcase}_dashboard" %>

app/views/fronts/forgot_password.html.erb
<div class="page-header">
	<h4>
		<%= t("general.forgot_password") %>
	</h4>
</div>
<%= form_for @user, :url => forgot_password_path, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <div class="controls">
      <% if flash[:forgot_pass_error] %>
      	<span class="text-error"><%= flash[:forgot_pass_error] %></span>
  		<% end %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.text_field :email, :class => 'input-xlarge', :placeholder => 'Email' %>
    </div>
  </div>

  <div class="form-actions">
    <div class="row-fluid">
      <div class="span12">
        <%= f.submit t("general.reset_password"), :class => 'btn btn-primary' %>
      </div><!--/span-->
    </div><!--/row-->
  </div>
<% end %>

app/views/fronts/other.html.erb
<% if @o_single %>
	<div class="page-header">
		<h4>
			<%= @o_single.name %>
		</h4>
	</div>
	<div class="container pt60">
		<p><%= @o_single.content.html_safe unless @o_single.content.blank? %></p>
	</div>	
<% else %>
  <h4><%= t("page_not_found") %></h4>
<% end %>

app/views/fronts/profile.html.erb
<div class="page-header">
	<h4>
		<%= t("general.profile") %>
	</h4>
</div>
<%= form_for @o_single, :url => profile_path, :html => { :class => 'form-horizontal' } do |f| %>
    <div class="control-group">
      <%= f.label :first_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :first_name, :class => 'input-xlarge' %>
      </div>
    </div>		
		
    <div class="control-group">
      <%= f.label :last_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_name, :class => 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %><span class="redStart">*</span>
      <div class="controls">
        <%= f.text_field :email, :class => 'input-xlarge' %>
       	<% if @o_single.errors[:email].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:email].first %></span>
      	<% end %>        
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :birth_date, :class => 'control-label' %>
      <div id="user_birth_date" class="controls">
		<%= f.text_field :birth_date, :class => 'input-xlarge' %>
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span> 				
	  </div>	   
    </div>
		 
    <div class="control-group">
        <%= f.label :image, :class => 'control-label' %>
        <div class="controls">
            <%= f.file_field :image, :class => 'input-xlarge' %>
        </div>
    </div>
    <% if @o_single.image? %>
        <div class="control-group"><div class="controls"><%= image_tag @o_single.image_url(:logo) %></div></div>
    <% end %>
    
	<div class="form-actions">
        <div class="row-fluid mb10">
            <div class="span12">
                <%= f.submit t("general.save"), :class => 'btn btn-primary' %>
            </div><!--/span-->
        </div><!--/row-->
    </div>
<% end %>

<script type="text/javascript">

$('#user_birth_date').datetimepicker({
    language: 'en',
    format: "dd/MM/yyyy"
  });

</script>  

app/views/fronts/show_search_box.js.erb
$("#div_update_search").show();
$("#spinner").hide();
<% if params[:toggle] == "true" %>
	$("#div_update_search").html("<%= escape_javascript(render("search")) %>");
<% else %>
	$("#div_update_search").html(" ");
<% end %>