config/routes.rb
ProjectApp::Application.routes.draw do
  # Here namespace admin belongs to super admin role
  namespace :admin do
    resources :users, :settings, :footer_pages, :contacts, :languages, :email_templates, :schools
    get '/updateschool/:id' => 'schools#updateschool', :as => :updateschool
  end

  resources :user_sessions

  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup(/:registration_key)' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]

  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
  get 'dashboard' => 'fronts#dashboard', :as => :dashboard
  match 'activate/:activation_key' => 'fronts#user_activation', :as => :activation_link, via: [:get]
  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box
  match 'contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other

  # user schools
  #get '/schools' => 'schools#index', :as => :schools
  resources :schools

  # You can have the root of your site routed with "root"
  root 'fronts#dashboard'

end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, :email, :user_id, :presence => true
  belongs_to :user
end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < ApplicationController
  before_filter :set_school, only: [:edit, :update, :destroy]
  before_filter :get_users, only: [:new, :create, :edit, :update]
  #before_action :require_superadmin, excpet: [:updateschool] 
  
  require 'will_paginate/array'

  def index
    @o_single = School.new
    
    session[:search_params] = params[:school] ? params[:school] : nil

    session[:set_pager_number] = params[:set_pager_number] if params[:set_pager_number]

    if session[:set_pager_number].nil?
      session[:set_pager_number] = PER_PAGE
    end

    @schools = School.order(sort_column + " " + sort_direction).paginate(:per_page => session[:set_pager_number], :page => params[:page])

    @params_arr = ['name']

  end

  def new
    @o_single = School.new
  end

  def create
    @o_single = School.new(school_params)
    flash[:notice] = nil
    if @o_single.save
      flash[:notice] = 'School was successfully created.'
    end
  end

  def edit
  end

  def update
    @o_single = School.find(params[:id])
    flash[:notice] = nil
    if @o_single.update_attributes(school_params)
      flash[:notice] = 'School was successfully updated.'
    end    
  end

  def destroy
    @o_single.destroy
    flash[:notice] = 'School was successfully deleted.'

    session[:search_params] = params[:school] ? params[:school] : nil

    session[:set_pager_number] = params[:set_pager_number] if params[:set_pager_number]

    if session[:set_pager_number].nil?
      session[:set_pager_number] = PER_PAGE
    end

    @schools = School.order(sort_column + " " + sort_direction).paginate(:per_page => session[:set_pager_number], :page => params[:page])
    
  end

  def updateschool
    begin
      @users = User.joins(:role).where(:roles => {:role_type => "Admin"})
      @o_single = School.find(params[:id])
    rescue => ex
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @o_single = School.find(params[:id])
    end

    def destroy_all_selected
      if params[:rec]
        id_arrs = params[:rec].collect { |k, v| k }
        School.find(id_arrs).map(&:destroy)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit!
    end

    def set_header_menu_active
      @users = "active"
    end

    def sort_column
      School.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def get_users
      @users = User.joins(:role).where(:roles => {:role_type => "Admin"})
    end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  require 'will_paginate/array'
  before_filter :set_school, only: [:edit, :update]
  before_filter :get_users, only: [:edit, :update]
  before_action :require_admin

  def index
    @o_single = School.new
    items_per_page = PER_PAGE

    if params[:page]
      page_count = params[:page].to_i
      total_limit = page_count * items_per_page
      session[:total_limit] = total_limit
    else
      page_count = 1
      total_limit = page_count * items_per_page
      session[:total_limit] = session[:total_limit] ? session[:total_limit] : total_limit
    end    
    
    school_query = current_user.schools.order("id desc")
    
    if (params[:school].present? and params[:school][:name].present?)
      params[:page] = params[:page] ? params[:page] : 1
      school_query = School.limit(session[:total_limit].to_i).order("id desc").all
      school_query = school_query.select {|s| s.name.include? params[:school][:name]}
    end

    if !params[:page] and !params[:school]
      session[:total_limit] = nil
    end
    
    @schools = school_query.paginate(:page => params[:page], :per_page => items_per_page)

    @params_arr = ['name']

  end

  def edit
  end

  def update
    @o_single = School.find(params[:id])
    flash[:notice] = nil
    if @o_single.update_attributes(school_params)
      flash[:notice] = 'School was successfully updated.'
    end    
  end

  private
  
    def school_params
      params.require(:school).permit!
    end
      
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @o_single = School.find(params[:id])
    end

    def get_users
      @users = User.joins(:role).where(:roles => {:role_type => "Admin"})
    end

end

app/helpers/admin/schools_helper.rb
module Admin::SchoolsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_fetchAll.html.erb
<% if @schools.size > 0 %>
  <% @schools.each do |o_row| %>
    <tr>
      <td><%= o_row.name %></td>
      <td><%= o_row.email %></td>
      <td><%= o_row.city %></td>
      <td><%= o_row.state %></td>
      <td><%= link_to t('general.edit'), edit_school_path(o_row), :class => 'btn btn-mini' %></td>
    </tr>
  <% end %>
<% else %>
  <tr>
    <td colspan="5">
			<%= t("general.record_not_found") %>
    </td>
  </tr>
<% end %>  

app/views/schools/_form.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success"><%= flash[:notice] %><% flash[:notice] = nil %></div>
<% end %>
<%= form_for @o_single, :remote => true, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.hidden_field :id, :value => params[:id] %>	

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'input-xlarge' %>
   	  <% if @o_single.errors[:name].any? %>
    	  <span class="text-error text-message"><%= @o_single.errors[:name].first %></span>
	    <% end %>
    </div>
  </div>
    
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'input-xlarge' %>
      <% if @o_single.errors[:email].any? %>
        <span class="text-error text-message"><%= @o_single.errors[:email].first %></span>
      <% end %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'input-xlarge' %>
     	<% if @o_single.errors[:phone].any? %>
      	<span class="text-error text-message"><%= @o_single.errors[:phone].first %></span>
    	<% end %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :mobile, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mobile, :class => 'input-xlarge' %>
     	<% if @o_single.errors[:mobile].any? %>
      	<span class="text-error text-message"><%= @o_single.errors[:mobile].first %></span>
    	<% end %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'input-xlarge' %>
      <% if @o_single.errors[:address].any? %>
        <span class="text-error text-message"><%= @o_single.errors[:address].first %></span>
      <% end %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'input-xlarge' %>
   	  <% if @o_single.errors[:state].any? %>
    	  <span class="text-error text-message"><%= @o_single.errors[:state].first %></span>
	    <% end %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'input-xlarge' %>
     	<% if @o_single.errors[:city].any? %>
      	<span class="text-error text-message"><%= @o_single.errors[:city].first %></span>
    	<% end %>
    </div>
  </div>

  <div class="form-actions">
    
      <div class="span12">
          <%= f.submit t("general.save"), :class => 'btn btn-success' %>
          <%= link_to t("general.cancel"), schools_path, :class => 'btn' %>
      </div><!--/span-->
    
  </div>
    
<% end %>

app/views/schools/_search.html.erb
<%= form_for @o_single, :method => "get", :remote => true, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend></legend>

 		<% @params_arr.each do |p| %>
	    <div class="control-group">
	      <%= f.label p.capitalize, :class => 'control-label' %>
	      <div class="controls">
	        <%= f.text_field p, :value => (session[:search_params] ? session[:search_params][p] : ""), :class => 'input-xlarge' %>
	      </div>
	    </div>
  	<% end %>
    <div class="controls">
      <%= f.submit t("general.search"), :class => 'btn btn-primary', :id => 'search_button_id' %>
      <span data-no-turbolink>
      <%= link_to 'Cancel', 'javascript:void(0)', :onclick => '$(this).closest("form").closest("div").hide()', :class => 'btn' %></span>
    </div>

  </fieldset>

<% end %>

app/views/schools/edit.html.erb
<%- model_class = School -%>
<div class="page-header">
  <h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
</div>
<div id="div_update_form">
  <!-- delete message model box -->
  <div id="myModal" class="modal hide fade" data-backdrop="static">
    <div class="modal-header">
        <h3>Confirmation</h3>
    </div>
    <div class="modal-body">
        <p>Some one deleted this record. Please, click Ok to reload page.</p>
    </div>
    <div class="modal-footer">
        <a href="<%= schools_path %>" class="btn">Ok</a>
    </div>
  </div>
  <!-- delete message model box end -->

	<%= render "form" %>
</div>

<script>
  $(function() {
    // Create a new client to connect to Faye
    var client = new Faye.Client('http://localhost:9292/faye');
 
    // Subscribe to the public channel
    var public_subscription = client.subscribe('/admin/schools/<%= @o_single.id %>/edit', function(data) {
      $.ajax({
        type: "GET",
        url: '/admin/updateschool/'+data.sid
      });
    });
  });
</script>

app/views/schools/index.html.erb
<%- model_class = School -%>

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<div class="page-header">
  <h4>
    <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> (<span id="count_records"><%= @schools.count %></span>)
    <div class="searchRight fr">
		  <%= link_to t("general.search"), show_search_box_path("true", model_class, @params_arr.join(',')), :remote => true, :class => 'btn btn-primary btn-small' %>&nbsp;
	  </div>
  </h4>
</div>

<div id="div_update_search">
	<% if session[:search_params] %>
		<% params[:model] = controller_name.classify %>
		<%= render "search" %>
	<% end %>
</div>

<div id="schools-list" class="schools">
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="20%"><%=raw t("name") %></th>
        <th width="20%"><%= t("email") %></th>
        <th width="15%"><%= t("city")%></th>
        <th width="15%"><%= t("state") %></th>
        <th width="10%"><%= t("general.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <%= render "fetchAll" %>
    </tbody>
  </table>
</div>


<div class="fr user-school-paging">
	<% if @schools.next_page %>
		<%= link_to "Load More Schools", schools_path(:page => @schools.next_page), :class => "load-more-schools", :remote => true %>
	<% end %>
</div>

<script type="text/javascript">
  $(function() {
    // Create a new client to connect to Faye
    var client = new Faye.Client('http://localhost:9292/faye');

    // Subscribe to the public channel
    var public_subscription = client.subscribe('/schools', function(data) {
      $.ajax({
        type: "GET",
        dataType: "script",
        url: '/' + data.text + '?faye=yes'
      });
    });
  });
</script>

app/views/schools/index.js.erb
$("#count_records").html("<%= @schools.count %>");

<% if params[:school] %>
	$("#schools-list table tbody").html("<%= escape_javascript(render("fetchAll")).html_safe %>");
<% else %>
	<% unless params[:faye] == 'yes' %>
		$("#schools-list table tbody").append("<%= escape_javascript(render("fetchAll")).html_safe %>");
		$('a.load-more-schools').attr('href', "<%= schools_path page: @schools.next_page %>");
	<% else %>
		$("#schools-list table tbody").html("<%= escape_javascript(render("fetchAll")).html_safe %>");
	<% end %>
<% end %>


<% if @schools.next_page %>
  $('.user-school-paging').html("<%= escape_javascript(link_to 'Load More Schools', schools_path(:page => @schools.next_page), :class => 'load-more-schools', :remote => true).html_safe %>");
<% else %>
  $('.user-school-paging a.load-more-schools').remove();
<% end %>

app/views/schools/update.js.erb
<% if @o_single.errors.any? %>
  $("#div_update_form").html("<%= escape_javascript(render("form")) %>");
<% else %>
var client = new Faye.Client('http://localhost:9292/faye');
client.publish('/admin/schools/<%= @o_single.id %>/edit', {
  sid: '<%= @o_single.id %>'
});

client.publish('/schools', { text: 'schools' });

client.publish('/admin/schools', { text: 'schools' });

<% end %>

app/views/schools/updateschool.js.erb
<% unless @o_single %>
  $("#myModal").modal('show');
<% else %>
  $("#div_update_form").html("<%= escape_javascript(render("form")) %>");
<% end %>