config/routes.rb
ProjectApp::Application.routes.draw do
  # Here namespace admin belongs to super admin role
  namespace :admin do
    resources :users, :settings, :footer_pages, :contacts, :languages, :email_templates, :schools
    get '/updateschool/:id' => 'schools#updateschool', :as => :updateschool
  end

  resources :user_sessions

  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup(/:registration_key)' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]

  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
  get 'dashboard' => 'fronts#dashboard', :as => :dashboard
  match 'activate/:activation_key' => 'fronts#user_activation', :as => :activation_link, via: [:get]
  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box
  match 'contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other

  # user schools
  #get '/schools' => 'schools#index', :as => :schools
  resources :schools

  # You can have the root of your site routed with "root"
  root 'fronts#dashboard'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

  remember_me_for 1.year
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  # GET /user_sessions
  def index
    redirect_to new_user_session_path
  end

  # GET login
  def new
    if current_user
      redirect_to root_path
    else   
      @user_session = UserSession.new
      respond_to do |format|
        format.html # new.html.erb
        format.xml { render :xml => @user_session }
      end
    end
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    respond_to do |format|
      if @user_session.save
        if current_user.is_active
          session[:user_id] = current_user.id
          session[:user_role] = current_user.role.role_type
          notice = t("general.login_successful")
          format.html { redirect_to(dashboard_path, :notice => notice) }
          format.xml { render :xml => @user_session, :status => :created, :location => @user_session }
        else
          reset_session
          @user_session = UserSession.new(params[:user_session])
          flash[:error] = t("general.you_are_not_active_user")
          format.html { render :action => "new" }
        end
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET logout
  def destroy
    @user_session = UserSession.find
    if @user_session
      @user_session.destroy
    end
    reset_session
    flash[:notice] = t("general.logout_successful")
    respond_to do |format|
      format.html { redirect_to "/" }
      format.xml { head :ok }
    end
  end

  # GET signup
  def signup
    @o_single = User.new

    if request.post?
      params[:user][:password_confirmation] = params[:user][:password]
      params[:user][:registration_key] = SecureRandom.hex(25)
      params[:user][:time_zone] = 'UTC'
      @o_single = User.new(user_params)

      respond_to do |format|
        if @o_single.save

          @o_single.role = Role.find_by(:role_type => USER)

          opts = {
            :username => @o_single.first_name, 
            :email => @o_single.email, 
            :password => params[:user][:password], 
            :registration_key => @o_single.registration_key
          }
          UserMailer.registration_confirmation(@o_single.email, opts).deliver

          @user_session = UserSession.new
          @user_session.email = @o_single.email
          @user_session.password = params[:user][:password]

          if @user_session.save
            session[:user_id] = current_user.id
            session[:user_role] = current_user.role.role_type
            notice = t("general.successfully_registered")
          end
          format.html { redirect_to dashboard_url, notice: notice }
          format.json { render action: 'show', status: :created, location: @o_single }
        else
          format.html { render action: 'signup' }
          format.json { render json: @o_single.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_session_params
      params[:user_session]
    end

    def user_params
      params.require(:user).permit!
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_for @user_session, :html => { :class => 'form-horizontal' } do |f| %>

	<% if flash[:error] %>
	  <div class="control-group">
	    <div class="controls">
			  <div class="alert-error" id="notice"><%= flash[:error] %></div>
			  <% flash[:error] = nil %>
	    </div>
	  </div>
	<% end %>    

  <div class="control-group">
    <div class="controls">
			<% @user_session.errors.full_messages.each do |msg| %>
				<% @msg_var = "general.#{msg.gsub(' ', "_")}" %>
				<span class="alert-error"><%= t(@msg_var) %></span>
			<% end %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.text_field :email, :placeholder => 'Email', :class => "input-xlarge" %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.password_field :password, :placeholder => 'Password', :class => "input-xlarge" %>
    </div>
  </div>

  <div class="form-actions">
		<%= f.submit t("general.login"), :class => 'btn btn-primary' %>
		<%= link_to t("general.click_here_to_recover_your_account"), forgot_password_path, :class => '' %>
  </div>

<% end %>

app/views/user_sessions/new.html.erb
<div class="page-header">
	<h4>
		<%= t("general.login") %>
	</h4>
</div>
<%= render :partial => 'form' %>

app/views/user_sessions/signup.html.erb
<div class="page-header">
	<h4>
		<%= t("general.sign_up") %>
	</h4>
</div>
<%= form_for @o_single, :url => signup_path, :html => { :class => 'form-horizontal' } do |f| %>
	<div class="control-group">
      <div class="controls">
        <%= f.text_field :first_name, :class => 'input-xlarge', :placeholder => 'First name' %>
       	<% if @o_single.errors[:email].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:first_name].first %></span>
      	<% end %>
      </div>
    </div>

	<div class="control-group">
      <div class="controls">
        <%= f.text_field :last_name, :class => 'input-xlarge', :placeholder => 'Last name' %>
       	<% if @o_single.errors[:last_name].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:last_name].first %></span>
      	<% end %>
      </div>
    </div>

	<div class="control-group">
      <div class="controls">
        <%= f.text_field :email, :class => 'input-xlarge', :placeholder => 'Email' %>
       	<% if @o_single.errors[:email].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:email].first %></span>
      	<% end %>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.password_field :password, :class => 'input-xlarge', :placeholder => 'Password' %>
       	<% if @o_single.errors[:password].any? %>
        	<span class="text-error text-message"><%= @o_single.errors[:password].first %></span>
      	<% end %>
      </div>
    </div>

    <div class="control-group">
      <div id="user_birth_date" class="controls">
		<%= f.text_field :birth_date, :class => 'input-xlarge', :placeholder => 'Birth Date' %>
        <span class="add-on">
            <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
        </span> 				
	</div>	   
    </div>
		 
    <div class="control-group">
        <div class="controls">
            <%= f.file_field :image, :class => 'input-xlarge' %>
        </div>
    </div>
    <% if @o_single.image? %>
        <div class="control-group"><div class="controls"><%= image_tag @o_single.image_url(:logo) %></div></div>
    <% end %>
    
    <div class="control-group">
      <div class="controls">
      	<div style="float:left;">
      		<%= f.check_box :term, :class => 'check_box' %>
  			<%= t("general.terms_and_conditions").html_safe %>
  			<span class="text-error text-message"><%= t("general.term_error") if @o_single.errors[:term].first %></span>
      	</div>
      </div>
    </div>	    
    
      <div class="form-actions">
          <div class="row-fluid">
              <div class="span12">
                  <%= f.submit t("general.sign_up"), :class => 'btn btn-primary' %>
              </div><!--/span-->
          </div><!--/row-->
      </div>
    
<% end %>

<script type="text/javascript">

$('#user_birth_date').datetimepicker({
    language: 'en',
    format: "dd/MM/yyyy"
  });

</script>  